"""Stable public catalogs used by directory APIs and the mini program."""

LANGUAGE_GROUPS = (
    ("priority", "常用"),
    ("southeast_asia", "东南亚"),
    ("east_asia", "东亚"),
    ("south_asia", "南亚"),
    ("middle_east_central_asia", "中东与中亚"),
    ("europe", "欧洲"),
    ("africa", "非洲"),
    ("americas_other", "美洲及其他"),
)

LANGUAGES = (
    ("vi", "越南语", "priority"),
    ("zh", "中文", "priority"),
    ("en", "英语", "priority"),
    ("th", "泰语", "southeast_asia"),
    ("lo", "老挝语", "southeast_asia"),
    ("km", "高棉语", "southeast_asia"),
    ("my", "缅甸语", "southeast_asia"),
    ("id", "印度尼西亚语", "southeast_asia"),
    ("ms", "马来语", "southeast_asia"),
    ("tl", "菲律宾语", "southeast_asia"),
    ("yue", "粤语", "east_asia"),
    ("ja", "日语", "east_asia"),
    ("ko", "韩语", "east_asia"),
    ("mn", "蒙古语", "east_asia"),
    ("hi", "印地语", "south_asia"),
    ("ur", "乌尔都语", "south_asia"),
    ("bn", "孟加拉语", "south_asia"),
    ("pa", "旁遮普语", "south_asia"),
    ("ta", "泰米尔语", "south_asia"),
    ("te", "泰卢固语", "south_asia"),
    ("mr", "马拉地语", "south_asia"),
    ("ne", "尼泊尔语", "south_asia"),
    ("si", "僧伽罗语", "south_asia"),
    ("ar", "阿拉伯语", "middle_east_central_asia"),
    ("fa", "波斯语", "middle_east_central_asia"),
    ("he", "希伯来语", "middle_east_central_asia"),
    ("tr", "土耳其语", "middle_east_central_asia"),
    ("ps", "普什图语", "middle_east_central_asia"),
    ("kk", "哈萨克语", "middle_east_central_asia"),
    ("uz", "乌兹别克语", "middle_east_central_asia"),
    ("ru", "俄语", "europe"),
    ("uk", "乌克兰语", "europe"),
    ("pl", "波兰语", "europe"),
    ("cs", "捷克语", "europe"),
    ("sk", "斯洛伐克语", "europe"),
    ("hu", "匈牙利语", "europe"),
    ("ro", "罗马尼亚语", "europe"),
    ("bg", "保加利亚语", "europe"),
    ("sr", "塞尔维亚语", "europe"),
    ("hr", "克罗地亚语", "europe"),
    ("sl", "斯洛文尼亚语", "europe"),
    ("de", "德语", "europe"),
    ("fr", "法语", "europe"),
    ("es", "西班牙语", "europe"),
    ("pt", "葡萄牙语", "europe"),
    ("it", "意大利语", "europe"),
    ("nl", "荷兰语", "europe"),
    ("da", "丹麦语", "europe"),
    ("sv", "瑞典语", "europe"),
    ("no", "挪威语", "europe"),
    ("fi", "芬兰语", "europe"),
    ("el", "希腊语", "europe"),
    ("sw", "斯瓦希里语", "africa"),
    ("am", "阿姆哈拉语", "africa"),
    ("ha", "豪萨语", "africa"),
    ("yo", "约鲁巴语", "africa"),
    ("zu", "祖鲁语", "africa"),
    ("af", "南非荷兰语", "africa"),
    ("ht", "海地克里奥尔语", "americas_other"),
)

SERVICES = (
    ("interpretation", "口译"),
    ("translation", "笔译"),
)

DOMAINS = (
    ("general", "通用"),
    ("business", "商务"),
    ("legal", "法律"),
    ("medical", "医疗健康"),
    ("finance", "金融财税"),
    ("it", "信息技术"),
    ("engineering", "工程技术"),
    ("manufacturing", "制造业"),
    ("construction", "建筑工程"),
    ("energy", "能源化工"),
    ("automotive", "汽车交通"),
    ("logistics", "物流供应链"),
    ("tourism", "旅游会展"),
    ("education", "教育培训"),
    ("media", "传媒出版"),
    ("government", "政府与公共事务"),
    ("agriculture", "农业食品"),
    ("environment", "环保"),
    ("patent", "专利知识产权"),
    ("sports", "体育文娱"),
)

LANGUAGE_CODES = frozenset(code for code, _label, _group in LANGUAGES)
SERVICE_CODES = frozenset(code for code, _label in SERVICES)
DOMAIN_CODES = frozenset(code for code, _label in DOMAINS)
SERVICE_MODES = frozenset({"online", "offline", "both"})
SUBJECT_TYPES = frozenset({"individual", "company"})
